from __future__ import annotations

"""Catalogue éditorial canonique de TomeLinea.

Une seule définition par identifiant de type. Les ordres Structure et
visuel ne sont que des vues sur ce même catalogue.
"""

from typing import Any

CATALOG_BY_TYPE: dict[str, dict[str, Any]] = {'couverture': {'type': 'couverture',
                'label': 'Couverture',
                'visual': 'cover',
                'family': 'ouverture',
                'current': True,
                'short_label': 'Couverture',
                'preview_image': 'assets/page_thumbnails/type_page_couverture.png',
                'custom': False,
                'duplicable': False,
                'structure_builtin': True},
 'deuxieme_couverture': {'type': 'deuxieme_couverture',
                         'label': '2e de couverture',
                         'visual': 'inside_cover',
                         'family': 'ouverture',
                         'current': True,
                         'structure_visual': 'cover',
                         'short_label': '2e couv.',
                         'preview_image': 'assets/page_thumbnails/type_page_deuxieme_couverture.png',
                         'custom': False,
                         'duplicable': False,
                         'structure_builtin': True},
 'page_titre': {'type': 'page_titre',
                'label': 'Page de titre',
                'visual': 'title',
                'family': 'ouverture',
                'current': True,
                'structure_visual': 'frontmatter',
                'short_label': 'Titre',
                'preview_image': 'assets/page_thumbnails/type_page_titre.png',
                'custom': False,
                'duplicable': True,
                'structure_builtin': True},
 'sommaire': {'type': 'sommaire',
              'label': 'Sommaire',
              'visual': 'toc',
              'family': 'ouverture',
              'current': True,
              'structure_visual': 'frontmatter',
              'short_label': 'Sommaire',
              'preview_image': 'assets/page_thumbnails/type_page_sommaire.png',
              'custom': False,
              'duplicable': True,
              'structure_builtin': True},
 'avant_propos': {'type': 'avant_propos',
                  'label': 'Avant-propos',
                  'visual': 'foreword',
                  'family': 'ouverture',
                  'current': True,
                  'structure_visual': 'frontmatter',
                  'short_label': 'Avant-propos',
                  'preview_image': 'assets/page_thumbnails/type_page_avant_propos.png',
                  'custom': False,
                  'duplicable': True,
                  'structure_builtin': True},
 'tete_partie': {'type': 'tete_partie',
                 'label': 'Tête de partie',
                 'visual': 'part_head',
                 'family': 'corps',
                 'current': True,
                 'structure_visual': 'section',
                 'short_label': 'Tête partie',
                 'preview_image': 'assets/page_thumbnails/type_page_tete_partie.png',
                 'custom': False,
                 'duplicable': True,
                 'structure_builtin': True},
 'chapitre': {'type': 'chapitre',
              'label': 'Chapitre',
              'visual': 'chapter',
              'family': 'corps',
              'current': True,
              'structure_visual': 'section',
              'short_label': 'Chapitre',
              'preview_image': 'assets/page_thumbnails/type_page_chapitre.png',
              'custom': False,
              'duplicable': True,
              'structure_builtin': True},
 'fiche': {'type': 'fiche',
           'label': 'Fiche',
           'visual': 'sheet',
           'family': 'corps',
           'current': True,
           'structure_visual': 'reference',
           'short_label': 'Fiche',
           'preview_image': 'assets/page_thumbnails/type_page_fiche.png',
           'custom': False,
           'duplicable': True,
           'structure_builtin': True},
 'texte': {'type': 'texte',
           'label': 'Texte',
           'visual': 'text',
           'family': 'corps',
           'current': True,
           'short_label': 'Texte',
           'preview_image': 'assets/page_thumbnails/type_page_texte.png',
           'custom': False,
           'duplicable': True,
           'structure_builtin': True},
 'illustration': {'type': 'illustration',
                  'label': 'Illustration',
                  'visual': 'image',
                  'family': 'corps',
                  'current': True,
                  'structure_visual': 'media',
                  'short_label': 'Illustration',
                  'preview_image': 'assets/page_thumbnails/type_page_illustration.png',
                  'custom': False,
                  'duplicable': True,
                  'structure_builtin': True},
 'transition': {'type': 'transition',
                'label': 'Transition',
                'visual': 'transition',
                'family': 'corps',
                'current': True,
                'structure_visual': 'section',
                'short_label': 'Transition',
                'preview_image': 'assets/page_thumbnails/type_page_transition.png',
                'custom': False,
                'duplicable': True,
                'structure_builtin': True},
 'page_blanche': {'type': 'page_blanche',
                  'label': 'Page blanche',
                  'visual': 'blank',
                  'family': 'structure',
                  'current': True,
                  'short_label': 'Blanche',
                  'preview_image': 'assets/page_thumbnails/type_page_blanche.png',
                  'custom': False,
                  'duplicable': True,
                  'structure_builtin': True},
 'conclusion': {'type': 'conclusion',
                'label': 'Conclusion',
                'visual': 'conclusion',
                'family': 'fin',
                'current': True,
                'structure_visual': 'backmatter',
                'short_label': 'Conclusion',
                'preview_image': 'assets/page_thumbnails/type_page_conclusion.png',
                'custom': False,
                'duplicable': True,
                'structure_builtin': True},
 'troisieme_couverture': {'type': 'troisieme_couverture',
                          'label': '3e de couverture',
                          'visual': 'inside_cover',
                          'family': 'fin',
                          'current': True,
                          'structure_visual': 'cover',
                          'short_label': '3e couv.',
                          'preview_image': 'assets/page_thumbnails/type_page_troisieme_couverture.png',
                          'custom': False,
                          'duplicable': False,
                          'structure_builtin': True},
 'quatrieme': {'type': 'quatrieme',
               'label': '4e de couverture',
               'visual': 'back_cover',
               'family': 'fin',
               'current': True},
 'personnalisee': {'type': 'personnalisee',
                   'label': 'Page personnalisée',
                   'visual': 'custom',
                   'family': 'corps',
                   'current': True},
 'faux_titre': {'type': 'faux_titre',
                'label': 'Faux-titre',
                'visual': 'title_light',
                'family': 'ouverture',
                'future': True},
 'frontispice': {'type': 'frontispice',
                 'label': 'Frontispice',
                 'visual': 'image',
                 'family': 'ouverture',
                 'future': True},
 'mentions_legales': {'type': 'mentions_legales',
                      'label': 'Mentions légales / Copyright',
                      'visual': 'legal',
                      'family': 'ouverture',
                      'future': True},
 'dedicace': {'type': 'dedicace',
              'label': 'Dédicace',
              'visual': 'dedication',
              'family': 'ouverture',
              'future': True,
              'structure_visual': 'frontmatter',
              'short_label': 'Dédicace',
              'preview_image': 'assets/page_thumbnails/type_page_dedicace.png',
              'custom': False,
              'duplicable': True,
              'structure_builtin': True},
 'epigraphe': {'type': 'epigraphe', 'label': 'Épigraphe', 'visual': 'quote', 'family': 'ouverture', 'future': True},
 'preface': {'type': 'preface',
             'label': 'Préface',
             'visual': 'foreword',
             'family': 'ouverture',
             'future': True,
             'structure_visual': 'frontmatter',
             'short_label': 'Préface',
             'preview_image': 'assets/page_thumbnails/type_page_preface.png',
             'custom': False,
             'duplicable': True,
             'structure_builtin': True},
 'avertissement': {'type': 'avertissement',
                   'label': 'Avertissement',
                   'visual': 'foreword',
                   'family': 'ouverture',
                   'future': True},
 'introduction': {'type': 'introduction',
                  'label': 'Introduction',
                  'visual': 'chapter',
                  'family': 'ouverture',
                  'future': True},
 'citation': {'type': 'citation',
              'label': 'Citation',
              'visual': 'quote',
              'family': 'corps',
              'future': True,
              'structure_visual': 'text',
              'short_label': 'Citation',
              'preview_image': 'assets/page_thumbnails/type_page_citation.png',
              'custom': False,
              'duplicable': True,
              'structure_builtin': True},
 'encadre': {'type': 'encadre',
             'label': 'Encadré',
             'visual': 'box',
             'family': 'corps',
             'future': True,
             'structure_visual': 'text',
             'short_label': 'Encadré',
             'preview_image': 'assets/page_thumbnails/type_page_encadre.png',
             'custom': False,
             'duplicable': True,
             'structure_builtin': True},
 'tableau': {'type': 'tableau',
             'label': 'Tableau',
             'visual': 'table',
             'family': 'corps',
             'future': True,
             'structure_visual': 'reference',
             'short_label': 'Tableau',
             'preview_image': 'assets/page_thumbnails/type_page_tableau.png',
             'custom': False,
             'duplicable': True,
             'structure_builtin': True},
 'graphique': {'type': 'graphique', 'label': 'Graphique', 'visual': 'chart', 'family': 'corps', 'future': True},
 'carte': {'type': 'carte',
           'label': 'Carte',
           'visual': 'map',
           'family': 'corps',
           'future': True,
           'structure_visual': 'media',
           'short_label': 'Carte',
           'preview_image': 'assets/page_thumbnails/type_page_carte.png',
           'custom': False,
           'duplicable': True,
           'structure_builtin': True},
 'chronologie': {'type': 'chronologie',
                 'label': 'Chronologie',
                 'visual': 'timeline',
                 'family': 'corps',
                 'future': True,
                 'structure_visual': 'reference',
                 'short_label': 'Chronologie',
                 'preview_image': 'assets/page_thumbnails/type_page_chronologie.png',
                 'custom': False,
                 'duplicable': True,
                 'structure_builtin': True},
 'portfolio': {'type': 'portfolio', 'label': 'Portfolio', 'visual': 'portfolio', 'family': 'corps', 'future': True},
 'double_page': {'type': 'double_page',
                 'label': 'Double page',
                 'visual': 'spread',
                 'family': 'corps',
                 'future': True},
 'annexe': {'type': 'annexe',
            'label': 'Annexe',
            'visual': 'appendix',
            'family': 'fin',
            'future': True,
            'structure_visual': 'backmatter',
            'short_label': 'Annexe',
            'preview_image': 'assets/page_thumbnails/type_page_annexe.png',
            'custom': False,
            'duplicable': True,
            'structure_builtin': True},
 'postface': {'type': 'postface', 'label': 'Postface', 'visual': 'foreword', 'family': 'fin', 'future': True},
 'notes': {'type': 'notes', 'label': 'Notes', 'visual': 'notes', 'family': 'fin', 'future': True},
 'glossaire': {'type': 'glossaire',
               'label': 'Glossaire',
               'visual': 'glossary',
               'family': 'fin',
               'future': True,
               'structure_visual': 'backmatter',
               'short_label': 'Glossaire',
               'preview_image': 'assets/page_thumbnails/type_page_glossaire.png',
               'custom': False,
               'duplicable': True,
               'structure_builtin': True},
 'lexique': {'type': 'lexique', 'label': 'Lexique', 'visual': 'glossary', 'family': 'fin', 'future': True},
 'bibliographie': {'type': 'bibliographie',
                   'label': 'Bibliographie',
                   'visual': 'references',
                   'family': 'fin',
                   'future': True,
                   'structure_visual': 'backmatter',
                   'short_label': 'Bibliographie',
                   'preview_image': 'assets/page_thumbnails/type_page_bibliographie.png',
                   'custom': False,
                   'duplicable': True,
                   'structure_builtin': True},
 'sources': {'type': 'sources', 'label': 'Sources', 'visual': 'references', 'family': 'fin', 'future': True},
 'index': {'type': 'index',
           'label': 'Index',
           'visual': 'index',
           'family': 'fin',
           'future': True,
           'structure_visual': 'backmatter',
           'short_label': 'Index',
           'preview_image': 'assets/page_thumbnails/type_page_index.png',
           'custom': False,
           'duplicable': True,
           'structure_builtin': True},
 'credits': {'type': 'credits',
             'label': 'Crédits iconographiques',
             'visual': 'credits',
             'family': 'fin',
             'future': True},
 'remerciements': {'type': 'remerciements',
                   'label': 'Remerciements',
                   'visual': 'dedication',
                   'family': 'fin',
                   'future': True,
                   'structure_visual': 'backmatter',
                   'short_label': 'Remerciements',
                   'preview_image': 'assets/page_thumbnails/type_page_remerciements.png',
                   'custom': False,
                   'duplicable': True,
                   'structure_builtin': True},
 'biographie': {'type': 'biographie',
                'label': 'Biographie de l’auteur',
                'visual': 'bio',
                'family': 'fin',
                'future': True,
                'structure_label': 'Biographie',
                'structure_visual': 'backmatter',
                'short_label': 'Biographie',
                'preview_image': 'assets/page_thumbnails/type_page_biographie.png',
                'custom': False,
                'duplicable': True,
                'structure_builtin': True},
 'autres_ouvrages': {'type': 'autres_ouvrages',
                     'label': 'Autres ouvrages',
                     'visual': 'portfolio',
                     'family': 'fin',
                     'future': True},
 'quatrieme_couverture': {'type': 'quatrieme_couverture',
                          'label': '4e de couverture',
                          'short_label': '4e couv.',
                          'preview_image': 'assets/page_thumbnails/type_page_quatrieme_couverture.png',
                          'visual': 'cover',
                          'custom': False,
                          'duplicable': False,
                          'structure_builtin': True},
 'page_titre_partie': {'type': 'page_titre_partie',
                       'label': 'Page de partie',
                       'short_label': 'Page partie',
                       'preview_image': 'assets/page_thumbnails/type_page_page_titre_partie.png',
                       'visual': 'section',
                       'custom': False,
                       'duplicable': True,
                       'structure_builtin': True},
 'portrait': {'type': 'portrait',
              'label': 'Portrait',
              'short_label': 'Portrait',
              'preview_image': 'assets/page_thumbnails/type_page_portrait.png',
              'visual': 'media',
              'custom': False,
              'duplicable': True,
              'structure_builtin': True},
 'intercalaire': {'type': 'intercalaire',
                  'label': 'Intercalaire',
                  'short_label': 'Intercalaire',
                  'preview_image': 'assets/page_thumbnails/type_page_intercalaire.png',
                  'visual': 'section',
                  'custom': False,
                  'duplicable': True,
                  'structure_builtin': True},
 'exercice': {'type': 'exercice',
              'label': 'Exercice',
              'short_label': 'Exercice',
              'preview_image': 'assets/page_thumbnails/type_page_exercice.png',
              'visual': 'reference',
              'custom': False,
              'duplicable': True,
              'structure_builtin': True},
 'a_propos_auteur': {'type': 'a_propos_auteur',
                     'label': 'À propos de l’auteur',
                     'short_label': 'À propos auteur',
                     'preview_image': 'assets/page_thumbnails/type_page_a_propos_auteur.png',
                     'visual': 'backmatter',
                     'custom': False,
                     'duplicable': True,
                     'structure_builtin': True}}

STRUCTURE_ORDER: tuple[str, ...] = ('couverture',
 'deuxieme_couverture',
 'troisieme_couverture',
 'quatrieme_couverture',
 'page_blanche',
 'page_titre',
 'sommaire',
 'avant_propos',
 'dedicace',
 'preface',
 'page_titre_partie',
 'tete_partie',
 'chapitre',
 'texte',
 'citation',
 'encadre',
 'illustration',
 'portrait',
 'carte',
 'tableau',
 'chronologie',
 'fiche',
 'intercalaire',
 'transition',
 'exercice',
 'glossaire',
 'bibliographie',
 'index',
 'annexe',
 'biographie',
 'a_propos_auteur',
 'conclusion',
 'remerciements')

VISUAL_ORDER: tuple[str, ...] = ('couverture',
 'deuxieme_couverture',
 'page_titre',
 'sommaire',
 'avant_propos',
 'tete_partie',
 'chapitre',
 'fiche',
 'texte',
 'illustration',
 'transition',
 'page_blanche',
 'conclusion',
 'troisieme_couverture',
 'quatrieme',
 'personnalisee',
 'faux_titre',
 'frontispice',
 'mentions_legales',
 'dedicace',
 'epigraphe',
 'preface',
 'avertissement',
 'introduction',
 'citation',
 'encadre',
 'tableau',
 'graphique',
 'carte',
 'chronologie',
 'portfolio',
 'double_page',
 'annexe',
 'postface',
 'notes',
 'glossaire',
 'lexique',
 'bibliographie',
 'sources',
 'index',
 'credits',
 'remerciements',
 'biographie',
 'autres_ouvrages')

ALIASES: dict[str, str] = {'cover': 'couverture',
 'front_cover': 'couverture',
 '1re de couverture': 'couverture',
 '2e_couverture': 'deuxieme_couverture',
 'second_cover': 'deuxieme_couverture',
 'inside_front_cover': 'deuxieme_couverture',
 '2e de couverture': 'deuxieme_couverture',
 'deuxième de couverture': 'deuxieme_couverture',
 'deuxieme de couverture': 'deuxieme_couverture',
 'title_page': 'page_titre',
 'page de titre': 'page_titre',
 'titre': 'page_titre',
 'toc': 'sommaire',
 'table des matières': 'sommaire',
 'table des matieres': 'sommaire',
 'avant-propos': 'avant_propos',
 'avant propos': 'avant_propos',
 'tête de partie': 'tete_partie',
 'tete de partie': 'tete_partie',
 'part_head': 'tete_partie',
 'chapter': 'chapitre',
 'page de chapitre': 'chapitre',
 'tête de chapitre': 'chapitre',
 'tete de chapitre': 'chapitre',
 'page de texte': 'texte',
 'text': 'texte',
 'page courante': 'texte',
 'page commune': 'texte',
 'page image': 'illustration',
 'image': 'illustration',
 'blank': 'page_blanche',
 'page blanche': 'page_blanche',
 'page auto': 'page_blanche',
 '3e_couverture': 'troisieme_couverture',
 'third_cover': 'troisieme_couverture',
 'inside_back_cover': 'troisieme_couverture',
 '3e de couverture': 'troisieme_couverture',
 'troisième de couverture': 'troisieme_couverture',
 'troisieme de couverture': 'troisieme_couverture',
 '4e_couverture': 'quatrieme',
 'back_cover': 'quatrieme',
 '4e de couverture': 'quatrieme',
 'quatrième de couverture': 'quatrieme',
 'quatrieme de couverture': 'quatrieme',
 'personnalisée': 'personnalisee',
 'personnalisee': 'personnalisee',
 'appendix': 'annexe'}

def structure_builtin_catalog() -> list[dict[str, Any]]:
    result = []
    for key in STRUCTURE_ORDER:
        if key not in CATALOG_BY_TYPE:
            continue
        item = dict(CATALOG_BY_TYPE[key])
        if "structure_label" in item:
            item["label"] = item["structure_label"]
        if "structure_visual" in item:
            item["visual"] = item["structure_visual"]
        result.append({k: v for k, v in item.items() if not k.startswith("structure_")})
    return result

def visual_catalog() -> tuple[dict[str, Any], ...]:
    result = []
    for key in VISUAL_ORDER:
        if key not in CATALOG_BY_TYPE:
            continue
        item = dict(CATALOG_BY_TYPE[key])
        result.append({k: v for k, v in item.items() if not k.startswith("structure_")})
    return tuple(result)
